# Generated by Django 3.2.4 on 2021-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuvisethApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
