# Generated by Django 3.2.4 on 2021-08-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuvisethApp', '0002_auto_20210807_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Jaffna', 'Jaffna'), ('Galle', 'Galle')], max_length=150, null=True),
        ),
    ]
