# Generated by Django 3.2.4 on 2021-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuvisethApp', '0004_company_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='district',
            field=models.CharField(choices=[('Ampara', 'Ampara'), ('Anuradhapura', 'Anuradhapura'), ('Badulla', 'Badulla'), ('Baticaloa', 'Baticaloa'), ('Colombo', 'Colombo'), ('Galle', 'Galle'), ('Gampaha', 'Gampaha'), ('Hambantota', 'Hambantota'), ('Jaffna', 'Jaffna'), ('Kalutura', 'Kalutura'), ('Kandy', 'Kandy'), ('Kegalle', 'Kegalle'), ('kilinochchi', 'kilinochchi'), ('Kurunegala', 'Kurunegala'), ('Mannar', 'Mannar'), ('Matale', 'Matale'), ('Matara', 'Matara'), ('Monaragala', 'Monaragala'), ('Mullaitivu', 'Mullaitivu'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Polonnaruwa', 'Polonnaruwa'), ('Puttalam', 'Puttalam'), ('Ratnapura', 'Ratnapura'), ('Trincomalee', 'Trincomalee'), ('Vavuniya', 'Vavuniya')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Ampara', 'Ampara'), ('Anuradhapura', 'Anuradhapura'), ('Badulla', 'Badulla'), ('Baticaloa', 'Baticaloa'), ('Colombo', 'Colombo'), ('Galle', 'Galle'), ('Gampaha', 'Gampaha'), ('Hambantota', 'Hambantota'), ('Jaffna', 'Jaffna'), ('Kalutura', 'Kalutura'), ('Kandy', 'Kandy'), ('Kegalle', 'Kegalle'), ('kilinochchi', 'kilinochchi'), ('Kurunegala', 'Kurunegala'), ('Mannar', 'Mannar'), ('Matale', 'Matale'), ('Matara', 'Matara'), ('Monaragala', 'Monaragala'), ('Mullaitivu', 'Mullaitivu'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Polonnaruwa', 'Polonnaruwa'), ('Puttalam', 'Puttalam'), ('Ratnapura', 'Ratnapura'), ('Trincomalee', 'Trincomalee'), ('Vavuniya', 'Vavuniya')], max_length=150, null=True),
        ),
    ]
