# Generated by Django 3.2.4 on 2021-08-10 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SuvisethApp', '0005_auto_20210810_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='ServiceProvider',
        ),
    ]
