# Generated by Django 3.2.4 on 2021-08-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuvisethApp', '0006_rename_company_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('images', models.ImageField(blank=True, upload_to='category_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Single-Service', 'Single-Service'), ('Multiple-Service', 'Multiple-Service'), ('Full-Planner', 'Full-Planner')], max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('images', models.ImageField(blank=True, upload_to='package_pics')),
                ('price', models.CharField(max_length=50)),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuvisethApp.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='SuvisethApp.Category'),
        ),
    ]
