# Generated by Django 3.2.4 on 2021-08-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuvisethApp', '0007_auto_20210811_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='categories',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='categories',
            field=models.ManyToManyField(blank=True, to='SuvisethApp.Category'),
        ),
    ]
